### ISSUE TITLE
[Suggestion] Change default timeframe

### ISSUE THREAD

**Issue by arunavo4** [stash86/MultiMA_TSL#1]
Move the timeframe to 15m from 5m for this strategy. I tested it works better in 15m

**Comment by stash86** [comment]
First, thanks for the input. I tried using it on 15m tf live, performed ok, but sometimes it can make me nervous because of the long wait for sell. My next idea is using 15m tf for buy, and using 5m for sell. Gonna test it out to see if it's possible

**Comment by arunavo4** [comment]
@stash86 yea I think you are right fast dumps will be a bad thing for 15m
