### ISSUE TITLE
Forcebuy not working

### ISSUE THREAD

**Issue by jurekl** [stash86/MultiMA_TSL#2]
Hi!
Today I tried to test your strategy.
Quite quickly realized, that it was impossible to force the purchase of cryptocurrency (forcebuy, via web interface FreqUI).
This is made impossible by the *confirm_trade_entry()* function returning False, most likely (I haven't debugged the code) after checking the condition: 
```
        if ((rate > last_candle['close'])) :
            return False
```

i don't know if it's intentional, rather i guess it's a side effect :-)
I find forcebuy very useful when verifying that a strategy is working fine.

I will follow the progress with interest!

Regards,
Jurek

P.S.
I checked, after commenting these two lines of code,
I can buy the crypto I want.

**Comment by stash86** [comment]
ah yeah, that most probably be the cause. You can delete those two lines if you want to

**Comment by jurekl** [comment]
Of course, but you probably had an idea by inserting this condition there :-)
For now, I have commented on this piece, but I'm always curious about how the original version works.

Greetings!
