### ISSUE TITLE
Missing data fillup for CELO/USDT: before: 999 - after: 1023 - 2.4%

### ISSUE THREAD

**Issue by Interopnl** [stash86/MultiMA_TSL#3]
When running the bot in live mode i get a lot of these warnings, any idea what the cause is for this behavior?

Missing data fillup for CELO/USDT: before: 999 - after: 1023 - 2.4%

**Comment by arunavo4** [comment]
does it come when running live/dry?

**Comment by Interopnl** [comment]
In live mode, this is the config:

    "max_open_trades": 4,
    "stake_currency": "USDT",
    "stake_amount": "unlimited",
    "amend_last_stake_amount ": true,
    "tradable_balance_ratio": 0.99,
    "fiat_display_currency": "USD",
    "dry_run": false,
    "dry_run_wallet": 70,    
    "cancel_open_orders_on_exit": false,
    "ignore_buying_expired_candle_after": 90,
    "unfilledtimeout": {
      "buy": 30,
      "sell": 10,
      "unit": "seconds"
    },

**Comment by SeriousM** [comment]
I got this message in my logs too, but for many pairs.
Yesterday the bot didn't traded at all, could this be the reason?
Restarting the bot didn't fixed the problem, is there something I could do
to solve it?

**Comment by stash86** [comment]
Freqtrade uses dataframes of 1000 candles, Binance was down for 2 hours which is 24 candles, i.e. 2.4% of 1000. This means it will take 5000 minutes from when Binance was down before those messages disappear completely and there are no longer any gaps in the dataframe, that's approximately 3.5 days.

**Comment by SeriousM** [comment]
Very well explained, thank you!
